#![no_main]
//! Fuzz target for C0PL4ND's TOML configuration loader.
//!
//! `~/.config/c0pl4nd/config.toml` (or `%APPDATA%\c0pl4nd\config.toml`) is a
//! user-editable, **untrusted-at-rest** file: it can be hand-edited into any
//! shape, crash-truncated mid-write, or tampered with by another local process.
//! The loader is documented to surface a readable error — *never* a bare panic —
//! on a malformed file (see `ConfigError` and `Config::from_toml`). This target
//! feeds arbitrary fuzzer-generated bytes as TOML source and asserts the loader
//! never panics, overflows, hangs, or aborts.
//!
//! It drives the real public entry point `c0pl4nd_core::Config::from_toml`,
//! which runs the full pipeline the on-disk path uses:
//!   1. `toml::from_str` deserialisation (serde-default backfill of absent keys),
//!   2. `migrate` (the schema-version-gated one-time transforms, e.g. tint remap),
//!   3. `validate` (range + hex-color semantic checks).
//!
//! On any input that parses into a `Config`, it also exercises the derived
//! accessors the render path consults — `effective_ui_scale` (the NaN/inf guard
//! + clamp), `effects.effective_chromatic`, and
//! `keybindings.validate` (the conflict/empty-combo scan) — so an arithmetic or
//! slicing edge reachable only after a successful parse is still caught. It then
//! round-trips through `to_toml` + re-parse to exercise the serialise path on a
//! fuzzer-reached config shape.

use libfuzzer_sys::fuzz_target;
use std::path::Path;

use c0pl4nd_core::Config;

fuzz_target!(|data: &[u8]| {
    // TOML source is text. Only feed valid UTF-8 to the parser so the fuzzer
    // spends its energy on TOML *structure* and C0PL4ND's validation/migration
    // on top, rather than the trivial "invalid UTF-8 -> error" rejection (the
    // toml crate's lexer is fuzzed upstream).
    let Ok(src) = std::str::from_utf8(data) else {
        return;
    };

    // A fixed, syntactic path — the loader only uses it to label errors, never
    // touches the filesystem in `from_toml`.
    let path = Path::new("fuzz-config.toml");

    if let Ok(cfg) = Config::from_toml(src, path) {
        // The config parsed AND passed validation + migration. Touch every
        // derived accessor the render/UI path consults, so any panic/overflow
        // reachable only after a successful parse is surfaced.
        let _ = cfg.effective_ui_scale(); // NaN/inf guard + 0.5..=3.0 clamp
        let _ = cfg.effects.effective_chromatic(); // toggle-gated, floored
        let _ = cfg.keybindings.validate(); // conflict / empty-combo scan
        for (_name, combo) in cfg.keybindings.entries() {
            let _ = combo.len();
        }

        // Round-trip: serialise the fuzzer-reached config and re-parse it. The
        // serialise path (`to_toml`) and a second parse must also stay panic-
        // free on any shape the fuzzer can construct.
        if let Ok(serialised) = cfg.to_toml() {
            let _ = Config::from_toml(&serialised, path);
        }
    }
});
