#![no_main]
//! Fuzz target for the C0PL4ND hand-written Sixel decoder.
//!
//! Sixel image data arrives over the PTY inside a DCS (`DCS ... q <data> ST`)
//! payload emitted by ANY program running in the terminal — it is fully
//! untrusted input. `decode_sixel` is a hand-written byte state-machine
//! (palette parsing, RLE `!N` repeats, band advance, sparse pixel map, integer
//! arithmetic on attacker-controlled counts) — exactly the class of code that
//! must never panic, hang, overflow, or OOB on a malformed or hostile stream.
//! This target feeds arbitrary fuzzer-generated bytes straight into the public
//! `c0pl4nd_core::image::decode_sixel` entry point and only checks that it
//! RETURNS (an `Option`); a `None` on garbage is correct, a panic is a bug.

use libfuzzer_sys::fuzz_target;

use c0pl4nd_core::image::decode_sixel;

fuzz_target!(|data: &[u8]| {
    // Drive the decoder with the raw, untrusted bytes. The decoder is pure and
    // returns `Option<DecodedImage>`; we never `unwrap()` the result into a
    // panic — only confirm the call returns. Touch the decoded fields so any
    // inconsistency reachable only through the produced image is observed.
    if let Some(img) = decode_sixel(data) {
        // Read derived state so the fuzzer detects an internally-inconsistent
        // image (e.g. a width/height that disagrees with the buffer length).
        let _ = img.width;
        let _ = img.height;
        let _ = img.rgba.len();
    }
});
