#![no_main]
//! Fuzz target for the C0PL4ND VT / ANSI / OSC escape-sequence parser.
//!
//! A terminal emulator's parser consumes bytes produced by ANY program running
//! inside the terminal — that is fully untrusted input. A malformed or hostile
//! escape sequence must never crash, panic, hang, or corrupt the grid model.
//! This target feeds arbitrary fuzzer-generated bytes straight into
//! `Terminal::advance`, the same entry point the PTY reader uses for live
//! shell output, and then reads back the public surface to make sure the
//! resulting state stays internally consistent (no out-of-bounds, no panic).

use libfuzzer_sys::fuzz_target;

use c0pl4nd_core::Terminal;

fuzz_target!(|data: &[u8]| {
    // A small, fixed screen keeps each iteration fast while still exercising
    // wrap, scroll, and cursor-clamp logic. Scrollback is enabled so the
    // history/scroll paths are covered too.
    let mut term = Terminal::with_scrollback(24, 80, 1000);

    // Drive the parser in arbitrarily-sized chunks. Splitting the input forces
    // the parser to handle escape sequences that straddle `advance()` calls —
    // the realistic case where a sequence is split across PTY reads. The first
    // byte selects a chunk size in 1..=64; the remainder is the payload.
    let (chunk_hint, payload) = match data.split_first() {
        Some((h, rest)) => (((*h as usize) % 64) + 1, rest),
        None => return,
    };

    for chunk in payload.chunks(chunk_hint) {
        term.advance(chunk);
    }

    // Touch the public read surface so the fuzzer detects any inconsistency
    // (panics / OOB) reachable only by reading derived state after parsing.
    let _ = term.title();
    let _ = term.cwd();
    let _ = term.prompt_marks();
    let _ = term.hyperlinks();
    let _ = term.images();
    let _ = term.scrollback_len();
    let _ = term.grid();
    let _ = term.display_rows();
    let _ = term.all_lines();
});
